# Generated by Django 5.1 on 2024-09-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
