# Generated by Django 5.1 on 2024-09-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='note',
            field=models.TextField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
