# Generated by Django 5.1 on 2024-09-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stock_note_alter_stock_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='note',
            field=models.TextField(default='null', editable=False, max_length=200),
        ),
    ]
