# Generated by Django 5.1 on 2024-09-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stock_unity_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.CharField(default='null', editable=False, max_length=100),
        ),
    ]
