# Generated by Django 5.1 on 2024-09-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stock_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='note',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='unity_value',
        ),
    ]
