# Generated by Django 5.1 on 2024-08-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.IntegerField(max_length=5)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=6)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
