# Generated by Django 5.1 on 2024-08-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='value',
        ),
    ]
