# Generated by Django 5.1 on 2024-09-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
    ]
