# Generated by Django 5.1 on 2024-09-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_sale_quantity_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
        migrations.AddField(
            model_name='sale',
            name='unity_value',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
    ]
