# Generated by Django 5.1 on 2024-09-03 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_sale_total_sale_unity_value'),
        ('stock', '0005_stock_unity_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unity_value',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
