# Generated by Django 5.1 on 2024-09-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_alter_sale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unity_value',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
    ]
